//using System;
//using System.Collections.Generic;
//using System.Text;

//namespace Ncp.Protobuf
//{
//    // This file was generated by a tool; you should avoid making direct changes.
//    // Consider using 'partial classes' to extend these types
//    // Input: my.proto

//#pragma warning disable CS1591, CS0612, CS3021, IDE1006
//    [global::ProtoBuf.ProtoContract()]
//    public partial class Packet : global::ProtoBuf.IExtensible
//    {
//        private global::ProtoBuf.IExtension __pbn__extensionData;
//        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
//            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

//        [global::ProtoBuf.ProtoMember(1, Name = @"sequence_id")]
//        public uint SequenceId { get; set; }

//        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
//        public byte[] Data { get; set; }

//        [global::ProtoBuf.ProtoMember(3, Name = @"ack_start_seq", IsPacked = true)]
//        public uint[] AckStartSeqs { get; set; }

//        [global::ProtoBuf.ProtoMember(4, Name = @"ack_seq_count", IsPacked = true)]
//        public uint[] AckSeqCounts { get; set; }

//        [global::ProtoBuf.ProtoMember(5, Name = @"bytes_read")]
//        public ulong BytesRead { get; set; }

//        [global::ProtoBuf.ProtoMember(6, Name = @"client_ids")]
//        public global::System.Collections.Generic.List<string> ClientIds { get; set; } = new global::System.Collections.Generic.List<string>();

//        [global::ProtoBuf.ProtoMember(7, Name = @"window_size")]
//        public uint WindowSize { get; set; }

//        [global::ProtoBuf.ProtoMember(8, Name = @"mtu")]
//        public uint Mtu { get; set; }

//        [global::ProtoBuf.ProtoMember(9, Name = @"close")]
//        public bool Close { get; set; }

//        [global::ProtoBuf.ProtoMember(10, Name = @"handshake")]
//        public bool Handshake { get; set; }

//    }

//#pragma warning restore CS1591, CS0612, CS3021, IDE1006

//}
